### ISSUE TITLE
Plugin no longer working

### ISSUE THREAD

**Issue by Tusam3** [travismx90/shiptime-woo#1]
Hello,

The plugin no longer works following an update.

Current versions:
WordPress: 5.4.1
WooCommerce: 4.1.0

Any insight would be appreciated as the plugin is no longer showing in the shipping method selection.

Thank you,

**Comment by travismx90** [comment]
V29 tested with WP 5.4.1 and Woo 4.1.0 - https://github.com/travismx90/shiptime-woo/commit/5f8ef3a1cf272104b080d436cb25531662ce7776

**Comment by Tusam3** [comment]
Tested here and new version works well. Thank you!
